services:
  nginx:
    image: nginx:1-alpine
    ports:
      -  '8000:80'
  mongo:
    image: mongo:8.0
  myapp:
    build: .
    environment:
      DOCKER_DB: true
    ports:
      - '8080:8080'
    volumes:
      - ./log:/root/log