services:
  mongo:
    image: mongo:4.2.5
  myapp:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/app/logs # creates log file upon running docker